# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRAiwl4fK_ztbRQ9-nuJibnRZYMhJMBa
"""

import streamlit as st
import pandas as pd

# Set app title
st.title("Bauxite Block Blending Calculator")

# Define the block data
data = [
    ["A", 5.15, 42.45, 27040000],
    ["B", 3.65, 45.26, 60320000],
    ["C", 2.522, 46.091, 47360000],
    ["D", 4.42, 44.72, 26560000],
    ["E", 3.404, 43.26, 15200000],
    ["F", 3.95, 44.79, 21593600],
    ["G", 2.38, 46.16, 13120000],
    ["H", 2.68, 46.35, 29920000],
]

# Convert to DataFrame
block_df = pd.DataFrame(data, columns=["Block", "Silica", "Alumina", "Volume"])

# Sidebar for selecting two blocks
st.sidebar.header("Select Two Blocks for Blending")
block_options = block_df["Block"].tolist()
block1 = st.sidebar.selectbox("Select Block 1", block_options)
block2 = st.sidebar.selectbox("Select Block 2", [b for b in block_options if b != block1])

# Fetch block data
b1 = block_df[block_df["Block"] == block1].iloc[0]
b2 = block_df[block_df["Block"] == block2].iloc[0]

# Perform blending calculations
total_volume = b1["Volume"] + b2["Volume"]
blended_silica = (b1["Silica"] * b1["Volume"] + b2["Silica"] * b2["Volume"]) / total_volume
blended_alumina = (b1["Alumina"] * b1["Volume"] + b2["Alumina"] * b2["Volume"]) / total_volume

# Display results
st.subheader("Blending Result")
st.write(f"**Blocks Selected**: {block1} & {block2}")
st.write(f"**Total Volume**: {total_volume:,.0f} m³")
st.write(f"**Blended Silica (%)**: {blended_silica:.2f}")
st.write(f"**Blended Alumina (%)**: {blended_alumina:.2f}")

# Optional: Show block data table
if st.checkbox("Show Block Data"):
    st.dataframe(block_df.set_index("Block"))

pip install streamlit